name: Publish Node SDK to Github Package Registry

on:
  push:
    branches:
      - main
    paths:
      - sdk/siminvest-node/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Install dependencies
      working-directory: sdk/siminvest-node
      run: npm i
    
    - name: Build client
      working-directory: sdk/siminvest-node
      run: npm run build

    - name: Publish package
      run: npm publish
      working-directory: sdk/siminvest-node
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
